a = int(input('Enter the number of the day of the week (January - 1; March - 3 etc): '))

if a == 1: print('The 1nd month of the year is January')
elif a == 2: print('The 2nd month of the year is February')
elif a == 3: print('The 3nd month of the year is March')
elif a == 4: print('The 4th month of the year is April')
elif a == 5: print('The 5th month of the year is May')
elif a == 6: print('The 6th month of the year is June')
elif a == 7: print('The 7th month of the year is July')
elif a == 8: print('The 8th month of the year is August')
elif a == 9: print('The 9th month of the year is September')
elif a == 10: print('The 10th month of the year is October')
elif a == 11: print('The 11th month of the year is November')
else: print('The 12th month of the year is December')